### ISSUE TITLE
ArticleSpecialのUIのズレを修正

### ISSUE THREAD

**Issue by takuma-ru** [takuma-ru/CupMENWeb#17]
ArticleSpecialの**販売状況を表示するUI**にずれが生じているので修正してほしい

![カップ麺サイト - Google Chrome 2021_01_25 12_24_19](https://user-images.githubusercontent.com/49429291/105657726-68596c00-5f08-11eb-837e-9a8966d3c364.png)

**Comment by takuma-ru** [comment]
@SuzuSys

**Comment by SuzuSys** [comment]
了解
