### ISSUE TITLE
Webページの実装

### ISSUE THREAD

**Issue by takuma-ru** [takuma-ru/CupMENWeb#5]
- **ページ**
  - Top画面
    - カップ麺の簡単な概要
    - 各社リンク
  - カップ麺の歴史
  - 各社の商品紹介（5社）
    - 企業について
    - 商品紹介
  - 東北のご当地カップ麺
    - 地図
    - 商品紹介
  - 海外のカップ麺
    - 商品紹介
  - コンビニ限定
    - 商品紹介

- **コンポーネント**
  - 共通
    - ヘッダー
  - Top画面
    - 各社リンクのitemコンポーネント
  - 各社の商品紹介
    - カップ麺情報のitemコンポーネント
    - 企業についてのコンポーネント

随時追加、削除

**Comment by takuma-ru** [comment]
役割分担

@takuma-ru 
- Top画面
- サンヨー食品
- ご当地
- 企業についてのコンポーネント
- 各社リンクのitemコンポーネント

@aoi-aoao 
- カップ麺の歴史
- エースコック
- 東洋水産
- ヘッダー

@SuzuSys 
- 海外のカップ麺
- コンビニ
- 日清
- カップ麺情報のitemコンポーネント

**Comment by takuma-ru** [comment]
@SuzuSys @aoi-aoao 
## 企業についてのコンポーネント(AboutCompany.vue)の使い方
```vue
<template>
  <Top :about="about" :slogan="slogan" :brand="brand"></Top>
</template>

<script>
import Top from '../components/AboutCompany'

export default {
  data(){
    return{
      about: "概要", //企業概要の内容
      slogan: "スローガン", //スローガンの内容
      brand: ['a', 's', 'd'] //ブランド一覧
    }
  },
  components: {
    Top
  }
}
</script>
```

**Comment by SuzuSys** [comment]
### ArticleComponentsの使いかた

- ArticleNormal.vue
   オリジナルのArticle
- ArticleSpecial.vue
    商品のstatusを表示。ご当地カップ麺に割り当てるのが適切
- ArticleOverseas.vue
    overseas.json用に作ったvueファイル。

例としてArticleOverseasを適用する。``<template>``内は
```
<div class="wrap">
  <ArticleOverseas v-for="(item, i) in $store.state.overseas" :key="i" :article-item="item"></ArticleOverseas>
</div>
```
とし、``<style>``内は
```
.wrap {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
  }
```
とする。
